# Generated by Django 4.0.5 on 2022-06-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_channel_state_controller_day_controller_esp_ap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='password',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='controller',
            name='prefix',
            field=models.CharField(default='', max_length=30),
        ),
    ]
