# Generated by Django 4.0.5 on 2022-07-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_userextension'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='name',
            field=models.CharField(default='Канал', max_length=64),
        ),
    ]
