# Generated by Django 4.0.5 on 2022-07-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_channel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
