# Generated by Django 4.0.5 on 2022-07-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_channel_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='weeks',
            field=models.SmallIntegerField(default=0),
        ),
    ]
