# Generated by Django 4.0.5 on 2022-07-27 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_program_cmax_program_cmin_program_lowlevel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='cmax',
        ),
        migrations.RemoveField(
            model_name='program',
            name='cmin',
        ),
        migrations.RemoveField(
            model_name='program',
            name='lowlevel',
        ),
        migrations.RemoveField(
            model_name='program',
            name='meandr_on',
        ),
        migrations.RemoveField(
            model_name='program',
            name='meaoff_cmax',
        ),
        migrations.RemoveField(
            model_name='program',
            name='meaoff_cmin',
        ),
        migrations.RemoveField(
            model_name='program',
            name='press_off',
        ),
        migrations.RemoveField(
            model_name='program',
            name='press_on',
        ),
        migrations.RemoveField(
            model_name='program',
            name='rainsens',
        ),
        migrations.RemoveField(
            model_name='program',
            name='season',
        ),
        migrations.RemoveField(
            model_name='program',
            name='tempsens',
        ),
    ]
