# Generated by Django 4.0.5 on 2022-08-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_channel_cmax_channel_cmin_channel_lowlevel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controller',
            name='num',
        ),
        migrations.AddField(
            model_name='controller',
            name='name',
            field=models.CharField(default='Controller', max_length=64),
        ),
    ]
