# Generated by Django 4.0.5 on 2022-08-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_controller_num_controller_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='host',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='controller',
            name='port',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='controller',
            name='user',
            field=models.CharField(default='', max_length=30),
        ),
    ]
