# Generated by Django 4.0.5 on 2022-08-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_controller_host_controller_port_controller_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
    ]
