# Generated by Django 4.0.5 on 2022-08-25 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_controller_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controller',
            old_name='host',
            new_name='mqtt_host',
        ),
        migrations.RenameField(
            model_name='controller',
            old_name='password',
            new_name='mqtt_password',
        ),
        migrations.RenameField(
            model_name='controller',
            old_name='port',
            new_name='mqtt_port',
        ),
        migrations.RenameField(
            model_name='controller',
            old_name='prefix',
            new_name='mqtt_prefix',
        ),
        migrations.RenameField(
            model_name='controller',
            old_name='user',
            new_name='mqtt_user',
        ),
    ]
