# Generated by Django 4.0.5 on 2022-08-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rename_host_controller_mqtt_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='volume_max',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='channel',
            name='volume_min',
            field=models.FloatField(default=0.0),
        ),
    ]
