# Generated by Django 4.0.5 on 2022-09-04 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_channel_volume_max_channel_volume_min'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='cmax',
            new_name='temp_max',
        ),
        migrations.RenameField(
            model_name='channel',
            old_name='cmin',
            new_name='temp_min',
        ),
    ]
